import { useState } from "react";
import { useWorkspace } from "../WorkspaceProvider";
import {
  InvoiceCard,
  OverlayActionButton,
  OverlayDialog,
  OverlayPreviewIcon,
  OverlaySaveIcon,
  SectionHeader
} from "../ui";
import {
  createInvoiceLineDraft,
  buildInvoicePdfFilename,
  buildInvoicesCsv,
  invoiceLinesTotal,
  invoicePaymentTotal,
  invoiceDisplayLabel,
  invoicePrefixForType,
  invoiceTemplateLabel,
  paymentMethodLabel,
  isAutoGeneratedInvoiceNumber,
  downloadTextFile,
  formatDate,
  money,
  suggestInvoiceNumber,
  toMoneyValue
} from "../../utils/formatters";
import { buildInvoicePrintHtml } from "../../utils/print/invoicePrintA4";
import { buildThermalReceiptPrintHtml } from "../../utils/print/invoicePrintThermal";

export function InvoicesPage() {
  const {
    data,
    forms,
    setForms,
    editor,
    beginCreateInvoiceWithPreset,
    beginEditInvoice,
    beginManagePayments,
    beginEditPayment,
    saveInvoice,
    savePayment,
    removeInvoice,
    removePayment,
    loading,
    closeEditor,
    user,
    workspaceSettings
  } = useWorkspace();

  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [clientFilter, setClientFilter] = useState("all");

  const isEditing = editor.kind === "invoice" && Boolean(editor.id);
  const invoiceLines = forms.invoice.lines?.length ? forms.invoice.lines : [createInvoiceLineDraft()];
  const invoiceTotalHT = invoiceLinesTotal(invoiceLines);
  const taxRateVal = Number(forms.invoice.taxRate || 20);
  const taxAmountVal = invoiceTotalHT * (taxRateVal / 100);
  const invoiceTotalTTC = invoiceTotalHT + taxAmountVal;
  const selectedCurrency = forms.invoice.currency || "EUR";

  const selectedClient = data.clients.find((client) => client.id === forms.invoice.clientId) || null;
  const selectedCreator = data.users.find((item) => item.id === forms.invoice.userId) || user || null;
  const isReceiptTemplate = forms.invoice.templateType === "receipt";
  const canAddInvoiceLine = (() => {
    const lastLine = invoiceLines[invoiceLines.length - 1] || createInvoiceLineDraft();
    const description = String(lastLine.description || "").trim();
    const quantity = String(lastLine.quantity ?? "").trim();
    const unitPrice = String(lastLine.unitPrice ?? "").trim();
    return !(description === "" && unitPrice === "" && (quantity === "" || Number(quantity) === 1));
  })();
  const paymentInvoice = editor.kind === "payment" ? data.invoices.find((invoice) => invoice.id === editor.invoiceId) || null : null;
  const paymentRows = paymentInvoice?.payments || [];
  const paymentRowsTotal = invoicePaymentTotal(paymentRows);
  const paymentBalance = Math.max(0, Number(paymentInvoice?.total || 0) - paymentRowsTotal);

  const filteredInvoices = data.invoices.filter((invoice) => {
    if (statusFilter !== "all" && invoice.status !== statusFilter) {
      return false;
    }
    if (clientFilter !== "all" && invoice.clientId !== clientFilter) {
      return false;
    }
    if (searchQuery.trim()) {
      const query = searchQuery.toLowerCase();
      const numMatch = String(invoice.number || "").toLowerCase().includes(query);
      const notesMatch = String(invoice.notes || "").toLowerCase().includes(query);
      const clientName = [invoice.client?.firstName, invoice.client?.lastName].filter(Boolean).join(" ").toLowerCase();
      const clientCompany = String(invoice.client?.company || "").toLowerCase();
      const clientMatch = clientName.includes(query) || clientCompany.includes(query);
      return numMatch || notesMatch || clientMatch;
    }
    return true;
  });

  function exportInvoicesCsv() {
    const filename = `factures-${new Date().toISOString().slice(0, 10)}.csv`;
    downloadTextFile(filename, buildInvoicesCsv(filteredInvoices), "text/csv;charset=utf-8");
  }

  function updateInvoiceLine(index, field, value) {
    setForms((current) => ({
      ...current,
      invoice: {
        ...current.invoice,
        lines: (current.invoice.lines?.length ? current.invoice.lines : [createInvoiceLineDraft()]).map((line, lineIndex) =>
          lineIndex === index ? { ...line, [field]: value } : line
        )
      }
    }));
  }

  function addInvoiceLine() {
    if (!canAddInvoiceLine) {
      return;
    }

    setForms((current) => ({
      ...current,
      invoice: {
        ...current.invoice,
        lines: [...(current.invoice.lines?.length ? current.invoice.lines : [createInvoiceLineDraft()]), createInvoiceLineDraft()]
      }
    }));
  }

  function removeInvoiceLine(index) {
    setForms((current) => {
      const lines = current.invoice.lines?.length ? current.invoice.lines : [createInvoiceLineDraft()];
      const nextLines = lines.filter((_, lineIndex) => lineIndex !== index);
      return {
        ...current,
        invoice: {
          ...current.invoice,
          lines: nextLines.length > 0 ? nextLines : [createInvoiceLineDraft()]
        }
      };
    });
  }

  function openInvoicePdf() {
    const filename = buildInvoicePdfFilename({
      invoice: {
        ...forms.invoice,
        lines: invoiceLines
      },
      client: selectedClient
    });
    const a4PrintHtml = buildInvoicePrintHtml({
      invoice: {
        ...forms.invoice,
        lines: invoiceLines
      },
      client: selectedClient,
      creator: selectedCreator,
      settings: workspaceSettings
    });

    const thermalPrintHtml = isReceiptTemplate
      ? buildThermalReceiptPrintHtml({
          invoice: {
            ...forms.invoice,
            lines: invoiceLines
          },
          client: selectedClient,
          creator: selectedCreator,
          settings: workspaceSettings
        })
      : "";

    const existingFrame = document.getElementById("invoice-print-frame");
    if (existingFrame) {
      existingFrame.remove();
    }

    const frame = document.createElement("iframe");
    frame.id = "invoice-print-frame";
    frame.title = filename.replace(/\.pdf$/i, "");
    frame.style.position = "fixed";
    frame.style.right = "0";
    frame.style.bottom = "0";
    frame.style.width = "0";
    frame.style.height = "0";
    frame.style.border = "0";
    frame.style.opacity = "0";
    frame.style.pointerEvents = "none";
    frame.setAttribute("aria-hidden", "true");

    let printed = false;
    let printTimer = null;

    const cleanup = () => {
      if (printTimer) {
        window.clearTimeout(printTimer);
        printTimer = null;
      }
      window.setTimeout(() => frame.remove(), 500);
    };

    const tryPrint = () => {
      if (printed) {
        return;
      }

      const frameWindow = frame.contentWindow;
      const frameDocument = frame.contentDocument;
      const frameBody = frameDocument?.body;
      if (!frameWindow || !frameBody || !frameBody.innerHTML.trim()) {
        return;
      }

      printed = true;
      frameWindow.onafterprint = () => {
        cleanup();
      };

      frameWindow.focus();
      frameWindow.print();
    };

    frame.onload = () => {
      const frameWindow = frame.contentWindow;
      if (!frameWindow) {
        cleanup();
        return;
      }

      printTimer = window.setTimeout(tryPrint, 150);
    };

    document.body.appendChild(frame);
    frame.srcdoc = isReceiptTemplate ? thermalPrintHtml : a4PrintHtml;
  }

  return (
    <div className="page-shell invoices-page">
      <header className="hero">
        <div>
          <span className="eyebrow">Facturation</span>
          <h1>Factures</h1>
        </div>
        <div className="hero-actions">
          <button className="secondary-button" type="button" onClick={() => beginCreateInvoiceWithPreset({ templateType: "professional" })}>
            Facture pro
          </button>
          <button className="secondary-button" type="button" onClick={() => beginCreateInvoiceWithPreset({ templateType: "receipt" })}>
            Reçu direct
          </button>
          <button className="secondary-button" type="button" onClick={exportInvoicesCsv}>
            Export CSV
          </button>
        </div>
      </header>

      <div className="page-scroll">
        <section className="content-grid invoices-layout">
          <div className="panel">
            <SectionHeader title="Cartes factures" />
            <div className="filters-panel">
              <div className="filters-grid">
                <label className="filter-field search">
                Rechercher
                <input
                  className="filter-input"
                  type="text"
                  placeholder="N° facture, client, notes..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                />
                </label>
                <label className="filter-field">
                Statut
                <select
                  className="filter-select"
                  value={statusFilter}
                  onChange={(e) => setStatusFilter(e.target.value)}
                >
                  <option value="all">Tous les statuts</option>
                  <option value="draft">Brouillon</option>
                  <option value="sent">Envoyée</option>
                  <option value="paid">Payée</option>
                  <option value="overdue">En retard</option>
                </select>
                </label>
                <label className="filter-field">
                Client
                <select
                  className="filter-select"
                  value={clientFilter}
                  onChange={(e) => setClientFilter(e.target.value)}
                >
                  <option value="all">Tous les clients</option>
                  {data.clients.map((c) => (
                    <option key={c.id} value={c.id}>
                      {c.firstName} {c.lastName}{c.company ? ` · ${c.company}` : ""}
                    </option>
                  ))}
                </select>
                </label>
              </div>
            </div>

            <div className="card-grid invoices-grid">
              {filteredInvoices.length > 0 ? (
                filteredInvoices.map((invoice) => (
                  <InvoiceCard
                    key={invoice.id}
                    invoice={invoice}
                    loading={loading}
                    onEdit={() => beginEditInvoice(invoice)}
                    onPayments={() => beginManagePayments(invoice)}
                    onDelete={() => removeInvoice(invoice.id)}
                  />
                ))
              ) : (
                <div className="empty-card-state">
                  Aucune facture ne correspond à vos critères.
                </div>
              )}
            </div>
          </div>
        </section>
      </div>

        <OverlayDialog
        open={editor.kind === "invoice"}
        title={isEditing ? "Modifier facture" : "Créer facture"}
        onClose={closeEditor}
        topbarActions={
          <>
            <OverlayActionButton
              icon={<OverlayPreviewIcon />}
              className="overlay-preview-button"
              type="button"
              onClick={openInvoicePdf}
              disabled={!forms.invoice.clientId}
            >
              {isReceiptTemplate ? "Aperçu thermique" : "Aperçu PDF"}
            </OverlayActionButton>
            <OverlayActionButton
              icon={<OverlaySaveIcon />}
              className="primary-button overlay-save-button"
              type="submit"
              form="invoice-form"
              disabled={loading || !forms.invoice.clientId}
            >
              {isEditing ? "Enregistrer" : "Créer facture"}
            </OverlayActionButton>
          </>
        }
        className={`invoice-editor-modal ${isReceiptTemplate ? "receipt-mode" : "professional-mode"}`}
      >
        <form className="stack-form invoice-form-grid" id="invoice-form" onSubmit={(event) => { event.preventDefault(); saveInvoice(); }}>

          <label className="invoice-form-field">
            Modèle
            <select
              value={forms.invoice.templateType}
              onChange={(event) => {
                const templateType = event.target.value;
                const prefix = invoicePrefixForType(templateType);
                setForms((current) => ({
                  ...current,
                  invoice: {
                    ...current.invoice,
                    templateType,
                    number:
                      !current.invoice.number || isAutoGeneratedInvoiceNumber(current.invoice.number)
                        ? suggestInvoiceNumber(data.invoices, prefix, current.invoice.issueDate)
                        : current.invoice.number
                  }
                }));
              }}
            >
              <option value="professional">Modèle professionnel - utilisateurs</option>
              <option value="receipt">Modèle receipt - service direct</option>
            </select>
          </label>
          <label className="invoice-form-field">
            Numéro
            <input
              value={forms.invoice.number}
              readOnly={!isEditing}
              onChange={(event) => setForms((current) => ({
                ...current,
                invoice: { ...current.invoice, number: event.target.value }
              }))}
            />
          </label>
          <label className="invoice-form-field">
            Client
            <select
              value={forms.invoice.clientId}
              onChange={(event) => setForms((current) => ({
                ...current,
                invoice: { ...current.invoice, clientId: event.target.value }
              }))}
            >
              <option value="">Sélectionner</option>
              {data.clients.map((client) => (
                <option key={client.id} value={client.id}>
                  {client.firstName} {client.lastName}{client.company ? ` · ${client.company}` : ""}
                </option>
              ))}
            </select>
          </label>
          <label className="invoice-form-field">
            Statut
            <select
              value={forms.invoice.status}
              onChange={(event) => setForms((current) => ({
                ...current,
                invoice: { ...current.invoice, status: event.target.value }
              }))}
            >
              <option value="draft">Brouillon</option>
              <option value="sent">Envoyée</option>
              <option value="paid">Payée</option>
              <option value="overdue">En retard</option>
            </select>
          </label>
          <label className="invoice-form-field">
            Devise
            <select
              value={forms.invoice.currency}
              onChange={(event) => setForms((current) => ({
                ...current,
                invoice: { ...current.invoice, currency: event.target.value }
              }))}
            >
              <option value="EUR">EUR</option>
              <option value="USD">USD</option>
              <option value="CDF">CDF</option>
            </select>
          </label>
          <label className="invoice-form-field">
            Taux de TVA (%)
            <input
              type="number"
              min="0"
              step="0.1"
              value={forms.invoice.taxRate}
              onChange={(event) => setForms((current) => ({
                ...current,
                invoice: { ...current.invoice, taxRate: event.target.value }
              }))}
            />
          </label>
          <label className="invoice-form-field">
            Date d'émission
            <input
              type="date"
              value={forms.invoice.issueDate}
              onChange={(event) => setForms((current) => ({
                ...current,
                invoice: { ...current.invoice, issueDate: event.target.value }
              }))}
            />
          </label>
          <label className="invoice-form-field">
            Échéance
            <input
              type="date"
              value={forms.invoice.dueDate}
              onChange={(event) => setForms((current) => ({
                ...current,
                invoice: { ...current.invoice, dueDate: event.target.value }
              }))}
            />
          </label>
          <div className="invoice-lines-editor invoice-form-span-2">
            <div className="invoice-lines-head">
              <div>
                <strong>Lignes de facture</strong>
              </div>
              <button
                className="ghost-button"
                type="button"
                onClick={addInvoiceLine}
                disabled={!canAddInvoiceLine}
              >
                Ajouter une ligne
              </button>
            </div>

            <div className="invoice-lines-table">
              <div className="invoice-lines-row invoice-lines-row-head">
                <span>N°</span>
                <span>Désignation</span>
                <span>Qte</span>
                <span>PU ({selectedCurrency})</span>
                <span>PT ({selectedCurrency})</span>
                <span>Action</span>
              </div>
              {invoiceLines.map((line, index) => {
                const lineTotal = toMoneyValue(line.quantity) * toMoneyValue(line.unitPrice);

                return (
                  <div className="invoice-lines-row" key={index}>
                    <span className="invoice-line-index">{index + 1}</span>
                    <label className="invoice-line-field">
                      <span className="sr-only">Désignation ligne {index + 1}</span>
                      <input
                        value={line.description}
                        onChange={(event) => updateInvoiceLine(index, "description", event.target.value)}
                        placeholder="Ex. Prestation de conseil"
                      />
                    </label>
                    <label className="invoice-line-field compact">
                      <span className="sr-only">Quantité ligne {index + 1}</span>
                      <input
                        type="number"
                        min="0"
                        step="1"
                        value={line.quantity}
                        onChange={(event) => updateInvoiceLine(index, "quantity", event.target.value)}
                      />
                    </label>
                    <label className="invoice-line-field compact">
                      <span className="sr-only">Prix unitaire ligne {index + 1}</span>
                      <input
                        type="number"
                        min="0"
                        step="0.01"
                        value={line.unitPrice}
                        onChange={(event) => updateInvoiceLine(index, "unitPrice", event.target.value)}
                        placeholder={`0.00 ${selectedCurrency}`}
                      />
                    </label>
                    <strong className="invoice-line-total">{money(lineTotal, selectedCurrency)}</strong>
                    <button className="ghost-button invoice-line-remove" type="button" onClick={() => removeInvoiceLine(index)}>
                      Supprimer
                    </button>
                  </div>
                );
              })}
            </div>

            <div className="invoice-lines-summary">
              <span>Total HT</span>
              <strong>{money(invoiceTotalHT, selectedCurrency)}</strong>
              <span>TVA ({taxRateVal}%)</span>
              <strong>{money(taxAmountVal, selectedCurrency)}</strong>
              <span className="invoice-total-label">Total TTC</span>
              <strong className="invoice-total-value">{money(invoiceTotalTTC, selectedCurrency)}</strong>
            </div>
          </div>
          <label className="invoice-form-field invoice-form-span-2">
            Notes
            <textarea
              rows="3"
              value={forms.invoice.notes}
              onChange={(event) => setForms((current) => ({
                ...current,
                invoice: { ...current.invoice, notes: event.target.value }
              }))}
            />
          </label>
        </form>
      </OverlayDialog>

      <OverlayDialog
        open={editor.kind === "payment"}
        title={`Paiements${paymentInvoice ? ` · ${invoiceDisplayLabel(paymentInvoice)}` : ""}`}
        onClose={closeEditor}
        className="payment-editor-modal"
        topbarActions={
          <button className="primary-button overlay-head-button" type="submit" form="payment-form" disabled={loading || !paymentInvoice}>
            {editor.id ? "Enregistrer" : "Ajouter le paiement"}
          </button>
        }
      >
        {paymentInvoice ? (
          <form className="stack-form invoice-form-grid" id="payment-form" onSubmit={(event) => { event.preventDefault(); savePayment(); }}>
            <label className="invoice-form-field">
              Montant
              <input
                type="number"
                min="0"
                step="0.01"
                value={forms.payment.amount}
                onChange={(event) => setForms((current) => ({
                  ...current,
                  payment: { ...current.payment, amount: event.target.value }
                }))}
              />
            </label>

            <label className="invoice-form-field">
              Méthode
              <select
                value={forms.payment.method}
                onChange={(event) => setForms((current) => ({
                  ...current,
                  payment: { ...current.payment, method: event.target.value }
                }))}
              >
                <option value="cash">Espèces</option>
                <option value="card">Carte</option>
                <option value="bank_transfer">Virement</option>
                <option value="mobile_money">Mobile money</option>
                <option value="check">Chèque</option>
                <option value="other">Autre</option>
              </select>
            </label>

            <label className="invoice-form-field">
              Date de paiement
              <input
                type="date"
                value={forms.payment.paidAt}
                onChange={(event) => setForms((current) => ({
                  ...current,
                  payment: { ...current.payment, paidAt: event.target.value }
                }))}
              />
            </label>

            <label className="invoice-form-field">
              Référence
              <input
                value={forms.payment.reference}
                onChange={(event) => setForms((current) => ({
                  ...current,
                  payment: { ...current.payment, reference: event.target.value }
                }))}
              />
            </label>

            <label className="invoice-form-field invoice-form-span-2">
              Notes
              <textarea
                rows="3"
                value={forms.payment.notes}
                onChange={(event) => setForms((current) => ({
                  ...current,
                  payment: { ...current.payment, notes: event.target.value }
                }))}
              />
            </label>

            <div className="invoice-form-span-2">
              <div className="quick-list">
                {paymentRows.length ? (
                  paymentRows.map((payment) => (
                    <article key={payment.id}>
                      <div>
                        <strong>{money(payment.amount, paymentInvoice.currency)}</strong>
                        <span>{paymentMethodLabel(payment.method)} · {formatDate(payment.paidAt)}</span>
                      </div>
                      <div className="entity-actions">
                        <button type="button" className="text-button" onClick={() => beginEditPayment(payment, paymentInvoice)}>
                          Modifier
                        </button>
                        <button type="button" className="text-button danger" onClick={() => removePayment(payment.id)}>
                          Supprimer
                        </button>
                      </div>
                    </article>
                  ))
                ) : (
                  <article>
                    <div>
                      <strong>Aucun paiement</strong>
                    </div>
                  </article>
                )}
              </div>
            </div>
          </form>
        ) : (
          <div className="overlay-hint">
            <strong>Facture introuvable</strong>
            <span>La facture sélectionnée n’est plus disponible.</span>
          </div>
        )}
      </OverlayDialog>
    </div>
  );
}
