import { useEffect, useMemo, useState } from "react";
import { createNeedRequest, deleteNeedRequest, getNeedRequests, rejectNeedRequest, submitNeedRequest, updateNeedRequest, validateNeedRequest } from "../../api";
import { useWorkspace } from "../WorkspaceProvider";
import { DataLoadingState, OverlayActionButton, OverlayDialog, OverlaySaveIcon, Table } from "../ui";
import { money, todayISO } from "../../utils/formatters";
import { buildNeedRequestPrintHtml } from "../../utils/print/needRequestPrint";

const statusLabels = { draft: "Brouillon", submitted: "Soumis", disbursed: "Décaissement effectué", rejected: "Rejeté" };
const priorityLabels = { low: "Basse", normal: "Normale", high: "Haute", urgent: "Urgente" };
function emptyLine() { return { description: "", quantity: "1", unit: "unité", unitPrice: "" }; }

export function NeedRequestsPage() {
  const { token, user, workspaceSettings, notifySuccess, notifyError } = useWorkspace();
  const [records, setRecords] = useState([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [open, setOpen] = useState(false);
  const [selected, setSelected] = useState(null);
  const [form, setForm] = useState({ department: "", purpose: "", issueDate: todayISO(), priority: "normal", currency: workspaceSettings.defaultCurrency || "EUR", notes: "", lines: [emptyLine()] });
  const [filter, setFilter] = useState("all");

  async function refresh() { setLoading(true); try { setRecords(await getNeedRequests(token)); } catch (error) { notifyError("États de besoins indisponibles", error.message); } finally { setLoading(false); } }
  useEffect(() => { refresh(); }, [token]);
  const filtered = useMemo(() => records.filter((record) => filter === "all" || record.status === filter), [records, filter]);
  const total = form.lines.reduce((sum, line) => sum + Number(line.quantity || 0) * Number(line.unitPrice || 0), 0);
  function updateLine(index, key, value) { setForm((current) => ({ ...current, lines: current.lines.map((line, lineIndex) => lineIndex === index ? { ...line, [key]: value } : line) })); }
  function resetForm() { setForm({ department: "", purpose: "", issueDate: todayISO(), priority: "normal", currency: workspaceSettings.defaultCurrency || "EUR", notes: "", lines: [emptyLine()] }); }
  function beginCreate() { setSelected(null); resetForm(); setOpen(true); }
  function beginEdit(record) { setSelected(record); setForm({ department: record.department, purpose: record.purpose, issueDate: record.issueDate.slice(0, 10), priority: record.priority || "normal", currency: record.currency || "EUR", notes: record.notes || "", lines: record.lines.map((line) => ({ description: line.description, quantity: String(line.quantity), unit: line.unit || "unité", unitPrice: String(line.unitPrice) })) }); setOpen(true); }
  async function save(event) { event.preventDefault(); if (saving) return; setSaving(true); try { const saved = selected ? await updateNeedRequest(token, selected.id, form) : await createNeedRequest(token, form); setRecords((current) => selected ? current.map((item) => item.id === saved.id ? saved : item) : [saved, ...current]); setOpen(false); setSelected(null); notifySuccess(selected ? "État modifié" : "État de besoins créé", "Il est enregistré comme brouillon."); } catch (error) { notifyError("Enregistrement impossible", error.message); } finally { setSaving(false); } }
  async function remove(record) { if (!window.confirm(`Supprimer l’état ${record.number} ?`)) return; try { await deleteNeedRequest(token, record.id); setRecords((current) => current.filter((item) => item.id !== record.id)); notifySuccess("État supprimé", record.number); } catch (error) { notifyError("Suppression impossible", error.message); } }
  function print(record) { const printWindow = window.open("", "_blank"); if (!printWindow) { notifyError("Impression impossible", "Autorisez les fenêtres contextuelles."); return; } printWindow.document.open(); printWindow.document.write(buildNeedRequestPrintHtml({ record, settings: workspaceSettings })); printWindow.document.close(); printWindow.focus(); window.setTimeout(() => { if (!printWindow.closed) printWindow.print(); }, 250); }
  async function action(record, type) {
    try {
      let updated;
      if (type === "submit") updated = await submitNeedRequest(token, record.id);
      if (type === "validate") updated = await validateNeedRequest(token, record.id);
      if (type === "reject") { const reason = window.prompt("Motif du rejet :", record.rejectedReason || ""); if (!reason?.trim()) return; updated = await rejectNeedRequest(token, record.id, reason); }
      setRecords((current) => current.map((item) => item.id === record.id ? updated : item));
      notifySuccess(type === "validate" ? "Décaissement effectué" : type === "reject" ? "État rejeté" : "État soumis", updated.cashDisbursement ? `Bon ${updated.cashDisbursement.number}` : updated.number);
    } catch (error) { notifyError("Action impossible", error.message); }
  }
  return <div className="page-shell cash-page">
    <header className="hero list-page-header"><div><span className="eyebrow">Achats et dépenses</span><h1>États de besoins</h1><p>Préparez un besoin puis transformez sa validation en décaissement de caisse.</p></div><div className="hero-actions"><button className="primary-button list-action-button" type="button" onClick={beginCreate}>Nouvel état de besoins</button></div></header>
    <div className="page-scroll"><section className="list-view-content"><div className="filters-panel list-filters"><label className="filter-field">Statut<select className="filter-select" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">Tous les statuts</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className="cash-total-line"><span>{filtered.length} état{filtered.length === 1 ? "" : "s"}</span></div></div>{loading ? <DataLoadingState label="Chargement des états de besoins…" /> : filtered.length ? <div className="panel entity-list-panel"><Table columns={["N°", "Date", "Service", "Objet", "Montant", "Statut", "Actions"]} rows={filtered.map((record) => [<strong>{record.number}</strong>, record.issueDate.slice(0, 10), record.department, record.purpose, <strong>{money(record.total, record.currency)}</strong>, <span className={`badge status-${record.status}`}>{statusLabels[record.status] || record.status}</span>, <div className="table-row-actions"><button className="text-button" type="button" onClick={() => print(record)}>Imprimer</button>{record.status === "draft" && <><button className="text-button" type="button" onClick={() => beginEdit(record)}>Modifier</button><button className="text-button danger" type="button" onClick={() => remove(record)}>Supprimer</button><button className="text-button" type="button" onClick={() => action(record, "submit")}>Soumettre</button></>}{["draft", "submitted"].includes(record.status) && ["admin", "director"].includes(user?.role) && <><button className="text-button" type="button" onClick={() => action(record, "validate")}>Valider et décaisser</button><button className="text-button danger" type="button" onClick={() => action(record, "reject")}>Rejeter</button></>}{record.cashDisbursement && <small>Bon : {record.cashDisbursement.number}</small>}</div>])} /></div> : <div className="empty-card-state">Aucun état de besoins à afficher.</div>}</section></div>
    <OverlayDialog open={open} title={selected ? `Modifier ${selected.number}` : "Nouvel état de besoins"} onClose={() => { setOpen(false); setSelected(null); }} topbarActions={<OverlayActionButton icon={<OverlaySaveIcon />} className="primary-button overlay-save-button" type="submit" form="need-request-form" disabled={saving}>{selected ? "Enregistrer" : "Créer l’état"}</OverlayActionButton>}><form id="need-request-form" className="stack-form invoice-form-grid" onSubmit={save}><label className="invoice-form-field">Service demandeur<input required maxLength="120" value={form.department} onChange={(event) => setForm({ ...form, department: event.target.value })} /></label><label className="invoice-form-field">Date<input type="date" required value={form.issueDate} onChange={(event) => setForm({ ...form, issueDate: event.target.value })} /></label><label className="invoice-form-field invoice-form-wide">Objet du besoin<input required maxLength="240" value={form.purpose} onChange={(event) => setForm({ ...form, purpose: event.target.value })} /></label><label className="invoice-form-field">Priorité<select value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })}>{Object.entries(priorityLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="invoice-form-field">Devise<select value={form.currency} onChange={(event) => setForm({ ...form, currency: event.target.value })}><option>EUR</option><option>USD</option><option>CDF</option></select></label><div className="proforma-lines invoice-form-wide"><div className="section-header"><h3>Besoins</h3><button className="text-button" type="button" onClick={() => setForm((current) => ({ ...current, lines: [...current.lines, emptyLine()] }))}>+ Ajouter</button></div>{form.lines.map((line, index) => <div className="proforma-line" key={index}><label>Désignation<input required value={line.description} onChange={(event) => updateLine(index, "description", event.target.value)} /></label><label>Qté<input required type="number" min="1" value={line.quantity} onChange={(event) => updateLine(index, "quantity", event.target.value)} /></label><label>Prix estimatif<input required type="number" min="0" step="0.01" value={line.unitPrice} onChange={(event) => updateLine(index, "unitPrice", event.target.value)} /></label></div>)}<strong>Total estimatif : {money(total, form.currency)}</strong></div><label className="invoice-form-field invoice-form-wide">Observations<textarea rows="3" maxLength="1000" value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label></form></OverlayDialog>
  </div>;
}
