import { escapeHtml, formatISODate, formatMoney } from "../formatters";
import { formatWorkspaceAddress, formatWorkspaceBankInfo, formatWorkspaceContact, formatWorkspaceLegalInfo } from "./invoicePrintShared";

function totalOut(report, currency) { return Number(report?.outTotals?.[currency] || 0) + Number(report?.depositTotals?.[currency] || 0); }

export function buildCashDailyReportPrintHtml({ report, settings = {} }) {
  const companyName = settings.companyName || "Mon entreprise";
  const address = formatWorkspaceAddress(settings);
  const contact = formatWorkspaceContact(settings);
  const legal = formatWorkspaceLegalInfo(settings);
  const bank = formatWorkspaceBankInfo(settings);
  const period = report?.period === "month";
  const sessions = report?.sessions || [];
  const inTotals = report?.inTotals || {};
  const outTotals = report?.outTotals || {};
  const depositTotals = report?.depositTotals || {};
  const netTotals = report?.netTotals || {};
  const balances = report?.totals || {};
  const currencies = [...new Set([...Object.keys(inTotals), ...Object.keys(outTotals), ...Object.keys(depositTotals), ...Object.keys(netTotals), ...Object.keys(balances)])];
  const operations = sessions.flatMap((session) => (session.movements || []).map((movement) => ({ ...movement, operator: session.operator?.name || session.operator?.email || "—" }))).sort((first, second) => new Date(first.createdAt) - new Date(second.createdAt));
  const summary = currencies.map((currency) => `<tr><th>${escapeHtml(currency)}</th><td class="in">+ ${escapeHtml(formatMoney(inTotals[currency] || 0, currency))}</td><td class="out">− ${escapeHtml(formatMoney(totalOut(report, currency), currency))}</td><td class="balance">${escapeHtml(formatMoney(period ? balances[currency] || 0 : netTotals[currency] || 0, currency))}</td></tr>`).join("");
  const rows = operations.map((movement, index) => `<tr><td>${index + 1}</td>${period ? `<td>${escapeHtml(formatISODate(movement.createdAt))}</td>` : ""}<td>${escapeHtml(movement.operator)}</td><td>${escapeHtml(movement.description || "—")}</td><td class="amount ${movement.type === "in" ? "in" : "out"}">${movement.type === "in" ? "+" : "−"} ${escapeHtml(formatMoney(movement.amount, movement.currency))}</td></tr>`).join("");
  const reportTitle = period ? "Rapport mensuel de caisse" : "Rapport journalier de caisse";
  const reportDate = period ? `Mois de ${formatISODate(report?.date).replace(/^1 /, "")}` : formatISODate(report?.date);
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>${escapeHtml(reportTitle)}</title><style>@page{size:A4;margin:16mm}*{box-sizing:border-box}body{margin:0;color:#0f172a;background:#fff;font:11px Inter,Arial,sans-serif}.page{min-height:265mm;display:flex;flex-direction:column}.top{display:grid;justify-items:center;gap:8px;margin-bottom:24px;padding:8px 0 20px;border-bottom:2px solid #0f172a;text-align:center}.logo{max-width:150px;max-height:72px;object-fit:contain}.company{font-size:20px;font-weight:750}.muted{color:#475569}.sector{color:#1d4ed8;font-weight:600}.title{text-align:center;margin-bottom:20px}.title h1{margin:0;font-size:18px;text-transform:uppercase}.title p{margin:6px 0;color:#64748b}.summary-table,.operations{width:100%;border-collapse:collapse}.summary-table{margin-bottom:22px}.summary-table th,.summary-table td,.operations th,.operations td{padding:9px 7px;border-bottom:1px solid #e2e8f0;text-align:left;vertical-align:top}.summary-table thead th,.operations th{color:#64748b;font-size:10px;text-transform:uppercase}.summary-table td:not(:first-child),.summary-table th:not(:first-child),.amount{text-align:right!important;white-space:nowrap}.summary-table .in,.amount.in{color:#15803d}.summary-table .out,.amount.out{color:#b91c1c}.summary-table .balance{font-size:14px;font-weight:800}.empty{text-align:center;color:#64748b;padding:28px}.footer{margin-top:auto;padding-top:14px;border-top:1px solid #cbd5e1;text-align:center;color:#475569;line-height:1.5}.footer span{display:block}.small{font-size:10px;margin-top:3px}</style></head><body><main class="page"><header class="top">${settings.logoDataUrl ? `<img class="logo" src="${escapeHtml(settings.logoDataUrl)}" alt="Logo ${escapeHtml(companyName)}">` : ""}<strong class="company">${escapeHtml(companyName)}</strong>${address ? `<span class="muted">${escapeHtml(address)}</span>` : ""}${contact ? `<span class="muted">${escapeHtml(contact)}</span>` : ""}${settings.businessSector ? `<span class="muted sector">${escapeHtml(settings.businessSector)}</span>` : ""}</header><section class="title"><h1>${escapeHtml(reportTitle)}</h1><p>${escapeHtml(reportDate)}</p></section><table class="summary-table"><thead><tr><th>Devise</th><th>Entrées</th><th>Sorties</th><th>Solde</th></tr></thead><tbody>${summary || `<tr><td colspan="4" class="empty">Aucune opération pour cette période.</td></tr>`}</tbody></table>${rows ? `<table class="operations"><thead><tr><th>#</th>${period ? "<th>Date</th>" : ""}<th>Opérateur</th><th>Description</th><th>Montant</th></tr></thead><tbody>${rows}</tbody></table>` : `<div class="empty">Aucune opération enregistrée pour cette période.</div>`}<footer class="footer"><span>${escapeHtml(companyName)}</span>${legal ? `<span class="small">${escapeHtml(legal)}</span>` : ""}${bank ? `<span class="small">${escapeHtml(bank)}</span>` : ""}</footer></main></body></html>`;
}
