import { escapeHtml, formatISODate, formatMoney } from "../formatters";
import { formatWorkspaceAddress, formatWorkspaceBankInfo, formatWorkspaceContact, formatWorkspaceLegalInfo } from "./invoicePrintShared";

export function buildCashDailyReportPrintHtml({ report, settings = {} }) {
  const companyName = settings.companyName || "Mon entreprise";
  const address = formatWorkspaceAddress(settings);
  const contact = formatWorkspaceContact(settings);
  const legal = formatWorkspaceLegalInfo(settings);
  const bank = formatWorkspaceBankInfo(settings);
  const sessions = report?.sessions || [];
  const totals = report?.totals || {};
  const totalLabel = report?.period === "month" ? "Solde net" : "Total théorique";
  const rows = sessions.flatMap((session) => (session.movements || []).map((movement) => ({ ...movement, operator: session.operator, session })))
    .map((movement) => `<tr><td>${escapeHtml(formatISODate(movement.createdAt))}</td><td>${escapeHtml(movement.session?.operator?.name || movement.operator?.email || "—")}</td><td>${escapeHtml(movement.type === "in" ? "Encaissement" : "Décaissement")}</td><td>${escapeHtml(movement.description || "—")}</td><td class="amount ${movement.type === "in" ? "in" : "out"}">${escapeHtml(formatMoney(movement.amount, movement.currency))}</td></tr>`).join("");

  const reportTitle = report?.period === "month" ? "Rapport mensuel de caisse" : "Rapport journalier de caisse";
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escapeHtml(reportTitle)}</title><style>
  @page{size:A4;margin:16mm}*{box-sizing:border-box}body{margin:0;color:#0f172a;background:#fff;font:11px Inter,Arial,sans-serif;-webkit-print-color-adjust:exact;print-color-adjust:exact}.page{min-height:265mm;display:flex;flex-direction:column}.top{display:grid;justify-items:center;gap:8px;margin-bottom:24px;padding:8px 0 20px;border-bottom:2px solid #0f172a;text-align:center}.logo{display:block;max-width:150px;max-height:72px;object-fit:contain}.company{font-size:20px;font-weight:750;line-height:1.2}.muted{color:#475569;font-size:11px;line-height:1.5}.sector{color:#1d4ed8;font-weight:600}.title{text-align:center;margin-bottom:20px}.title h1{margin:0;font-size:18px;text-transform:uppercase}.title p{margin:6px 0;color:#64748b}.summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:10px;margin-bottom:18px}.summary-card{padding:12px;border:1px solid #e2e8f0;border-radius:14px}.summary-card span{display:block;color:#64748b;font-size:10px;text-transform:uppercase}.summary-card strong{display:block;margin-top:5px;font-size:16px}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:8px 7px;border-bottom:1px solid #e2e8f0;text-align:left;vertical-align:top}.table th{color:#64748b;font-size:10px;text-transform:uppercase}.amount{text-align:right!important;white-space:nowrap;font-weight:700}.amount.in{color:#15803d}.amount.out{color:#b91c1c}.empty{text-align:center;color:#64748b;padding:28px}.footer{margin-top:auto;padding-top:14px;border-top:1px solid #cbd5e1;text-align:center;color:#475569;line-height:1.5}.footer span{display:block}.footer .small{font-size:10px;margin-top:3px}
  </style></head><body><main class="page"><header class="top">${settings.logoDataUrl ? `<img class="logo" src="${escapeHtml(settings.logoDataUrl)}" alt="Logo ${escapeHtml(companyName)}">` : ""}<strong class="company">${escapeHtml(companyName)}</strong>${address ? `<span class="muted">${escapeHtml(address)}</span>` : ""}${contact ? `<span class="muted">${escapeHtml(contact)}</span>` : ""}${settings.businessSector ? `<span class="muted sector">${escapeHtml(settings.businessSector)}</span>` : ""}</header><section class="title"><h1>${escapeHtml(reportTitle)}</h1><p>${escapeHtml(formatISODate(report?.date))}</p></section><section class="summary">${Object.entries(totals).map(([currency, amount]) => `<div class="summary-card"><span>${escapeHtml(totalLabel)} ${escapeHtml(currency)}</span><strong>${escapeHtml(formatMoney(amount, currency))}</strong></div>`).join("") || `<div class="summary-card"><span>Total</span><strong>—</strong></div>`}</section>${rows ? `<table class="table"><thead><tr><th>Date</th><th>Opérateur</th><th>Type</th><th>Description</th><th class="amount">Montant</th></tr></thead><tbody>${rows}</tbody></table>` : `<div class="empty">Aucun mouvement enregistré pour cette période.</div>`}<footer class="footer"><span>${escapeHtml(companyName)}</span>${legal ? `<span class="small">${escapeHtml(legal)}</span>` : ""}${bank ? `<span class="small">${escapeHtml(bank)}</span>` : ""}</footer></main></body></html>`;
}
