import { escapeHtml, formatISODate, formatMoney } from "../formatters";
import { formatWorkspaceAddress, formatWorkspaceBankInfo, formatWorkspaceContact, formatWorkspaceLegalInfo } from "./invoicePrintShared";

export function buildNeedRequestPrintHtml({ record, settings = {} }) {
  const companyName = settings.companyName || "Mon entreprise";
  const statusLabels = { draft: "Brouillon", submitted: "Soumis", rejected: "Rejeté", disbursed: "Décaissement effectué" };
  const priorityLabels = { low: "Basse", normal: "Normale", high: "Haute", urgent: "Urgente" };
  const statusLabel = record.status === "disbursed" ? `Décaissement effectué${record.cashDisbursement?.number ? ` · ${record.cashDisbursement.number}` : ""}` : (statusLabels[record.status] || record.status || "—");
  const lines = (record.lines || []).map((line) => `<tr><td>${escapeHtml(line.description)}</td><td>${escapeHtml(String(line.quantity))}</td><td>${escapeHtml(line.unit || "unité")}</td><td>${escapeHtml(formatMoney(line.unitPrice, record.currency))}</td><td>${escapeHtml(formatMoney(Number(line.unitPrice) * Number(line.quantity), record.currency))}</td></tr>`).join("");
  const address = formatWorkspaceAddress(settings);
  const contact = formatWorkspaceContact(settings);
  const legal = formatWorkspaceLegalInfo(settings);
  const bank = formatWorkspaceBankInfo(settings);
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>${escapeHtml(record.number)}</title><style>@page{size:A4;margin:16mm}body{font:11px Arial;color:#0f172a;margin:0}.page{min-height:265mm;display:flex;flex-direction:column}.head{text-align:center;border-bottom:2px solid #0f172a;padding-bottom:18px;margin-bottom:24px}.logo{max-width:150px;max-height:70px;object-fit:contain}.company{display:block;font-size:20px;font-weight:bold;margin:8px}.muted{display:block;color:#64748b;margin:3px}.title{text-align:center}.title h1{font-size:20px;text-transform:uppercase;margin:0}.meta{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:22px 0}.meta div{border:1px solid #e2e8f0;border-radius:10px;padding:10px}.meta span{display:block;color:#64748b;font-size:10px;text-transform:uppercase}.meta strong{display:block;margin-top:5px}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:8px;border-bottom:1px solid #e2e8f0;text-align:left}.table th{font-size:10px;color:#64748b;text-transform:uppercase}.right{text-align:right!important}.total{text-align:right;font-size:16px;margin-top:18px}.notes{margin-top:20px;padding:12px;background:#f8fafc;border-radius:10px}.footer{margin-top:auto;padding-top:14px;border-top:1px solid #cbd5e1;text-align:center;color:#475569}.footer span{display:block;margin:3px}.small{font-size:10px}</style></head><body><main class="page"><header class="head">${settings.logoDataUrl ? `<img class="logo" src="${escapeHtml(settings.logoDataUrl)}">` : ""}<strong class="company">${escapeHtml(companyName)}</strong>${address ? `<span class="muted">${escapeHtml(address)}</span>` : ""}${contact ? `<span class="muted">${escapeHtml(contact)}</span>` : ""}</header><section class="title"><h1>État de besoins</h1><p>${escapeHtml(record.number)}</p></section><section class="meta"><div><span>Service demandeur</span><strong>${escapeHtml(record.department)}</strong></div><div><span>Date</span><strong>${escapeHtml(formatISODate(record.issueDate))}</strong></div><div><span>Objet</span><strong>${escapeHtml(record.purpose)}</strong></div><div><span>Priorité</span><strong>${escapeHtml(priorityLabels[record.priority] || record.priority || "Normale")}</strong></div><div><span>Statut</span><strong>${escapeHtml(statusLabel)}</strong></div></section><table class="table"><thead><tr><th>Désignation</th><th>Qté</th><th>Unité</th><th class="right">Prix estimatif</th><th class="right">Total</th></tr></thead><tbody>${lines}</tbody></table><div class="total">Total estimatif : <strong>${escapeHtml(formatMoney(record.total, record.currency))}</strong></div>${record.notes ? `<div class="notes"><strong>Observations</strong><br>${escapeHtml(record.notes)}</div>` : ""}<footer class="footer"><span>${escapeHtml(companyName)}</span>${legal ? `<span class="small">${escapeHtml(legal)}</span>` : ""}${bank ? `<span class="small">${escapeHtml(bank)}</span>` : ""}</footer></main></body></html>`;
}
